#cloud-config
###
### mapletree.moe - kanade.mapletree.moe cloud-init
###
# system setup
fqdn: kanade.mapletree.moe
hostname: kanade
prefer_fqdn_over_hostname: true
create_hostname_file: true
timezone: Europe/Berlin

# ssh configuration
disable_root: true
disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding
ssh_deletekeys: true
ssh_genkeytypes: [ed25519]
ssh:
  emit_keys_to_console: false
allow_public_ssh_keys: true
ssh_pwauth: false

# user configuration
users:
  - name: podman
    gecos: Mapletree.moe Container User
    groups: users,podman
    primary_group: podman
  - name: mapletree
    gecos: Mapletree.moe Administrator
    groups: users,mapletree,docker,wheel
    primary_group: mapletree
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      # yamllint disable-line rule:line-length
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKuYlqIG3fsTfKt5xmvbzgxIp1pzh2xiJXGtyBo41DJB nagato@mapletree.com
